import * as React from 'react';
import {ArrowUpRight,ArrowDownRight,Plus,Check,MoreHorizontal,Mail,Search,ArrowRight,Folder,Globe,Lock,CheckCircle2,Copy,Download,Settings2,Send,Paperclip,CornerDownLeft,Palette,Code2,LayoutGrid,Heart,CalendarDays} from 'lucide-react';
import * as U from '../../../packages/ui/src/index';
const monthData=[{name:'Jan',value:32},{name:'Feb',value:48},{name:'Mar',value:37},{name:'Apr',value:65},{name:'May',value:52},{name:'Jun',value:82}];
function Panel({children,className='',title,description,action}:{children:React.ReactNode;className?:string;title?:string;description?:string;action?:React.ReactNode}){return <section className={'showcase-panel '+className}>{title&&<div className="mb-5 flex items-start justify-between gap-3"><div><h3 className="text-[13px] font-semibold tracking-tight">{title}</h3>{description&&<p className="mt-1.5 text-[11px] leading-relaxed text-muted">{description}</p>}</div>{action}</div>}{children}</section>}
function Row({children}:{children:React.ReactNode}){return <div className="flex items-center justify-between gap-3">{children}</div>}
export function Showcase({view='gallery'}:{view?:'gallery'|'workspace'}){
const [audience,setAudience]=React.useState('team'),[invite,setInvite]=React.useState(false),[toast,setToast]=React.useState(''),[name,setName]=React.useState(''),[compact,setCompact]=React.useState(true),[share,setShare]=React.useState(false),[period,setPeriod]=React.useState('6m'),[tab,setTab]=React.useState('Overview'),[message,setMessage]=React.useState(''),[messages,setMessages]=React.useState(['A space for the next good idea.']),[subscribed,setSubscribed]=React.useState(false),[theme,setTheme]=React.useState('System'),[dialogOpen,setDialogOpen]=React.useState(false);
const actions=[{label:'Duplicate',onSelect:()=>setToast('Example duplicated')},{label:'Export',onSelect:()=>setToast('Export prepared')},{label:'Move to archive',onSelect:()=>setToast('Example archived')}];
const menu=<U.DropdownMenu trigger={<U.Button tone="quiet" size="sm" aria-label="More actions"><MoreHorizontal className="size-4"/></U.Button>} items={actions}/>;
const data=period==='6m'?monthData:monthData.map(d=>({...d,value:Math.round(d.value*.7)}));
if(view==='workspace')return <div className="workspace-demo"><aside className="workspace-nav"><p className="mb-8 font-editorial text-xl">Studio / 01</p>{['Overview','Projects','Library','Activity','Settings'].map((n,i)=>{const Icon=[LayoutGrid,Folder,Code2,CalendarDays,Settings2][i];return <button key={n} onClick={()=>setTab(n)} className={'flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-start text-xs '+(tab===n?'bg-surface font-medium':'text-muted')}><Icon className="size-3.5"/>{n}</button>})}<div className="mt-auto rounded-lg border border-line p-3"><p className="text-xs font-medium">Your own beginning.</p><p className="mt-2 text-[11px] leading-relaxed text-muted">A little structure. More room for ideas.</p></div></aside><div className="min-w-0 p-5 md:p-8"><Row><div><p className="text-[10px] uppercase tracking-[.15em] text-muted">Studio / {tab}</p><h2 className="mt-2 font-editorial text-2xl">Good morning, Alex.</h2></div><U.Button size="sm" onClick={()=>setDialogOpen(true)}><Plus className="size-3.5"/>New project</U.Button></Row><div className="mt-7 grid gap-4 md:grid-cols-3">{[['Active projects','12','2 ready for review'],['Contributions','248','18 this week'],['Team members','8','Across 4 time zones']].map(([l,v,n])=><Panel key={l}><p className="text-[11px] text-muted">{l}</p><p className="my-3 text-3xl font-medium tracking-tight">{v}</p><p className="text-[10px] text-muted">{n}</p></Panel>)}</div><div className="mt-4 grid gap-4 lg:grid-cols-[1.5fr_1fr]"><Panel title="A little progress, every day." description="Your team's contribution history."><U.Chart data={data} label="Contributions" kind="area" compact/></Panel><Panel title="Ready for review">{['Component anatomy','Editorial homepage','Color tokens'].map((n,i)=><div className="flex items-center justify-between border-b border-line py-3 text-xs" key={n}><span>{n}</span><U.Badge tone={i?'neutral':'success'}>{i?'Draft':'Ready'}</U.Badge></div>)}</Panel></div><div className="mt-4"><Panel title="Your projects" action={menu}><U.DataTable rows={[{id:'1',name:'Sorgente design system',status:'Active',amount:120},{id:'2',name:'Field notes',status:'Review',amount:85},{id:'3',name:'Common ground',status:'Draft',amount:240}]}/></Panel></div></div><U.Modal open={dialogOpen} onOpenChange={setDialogOpen} title="A new beginning." description="Give your next idea a place to grow."><U.FormBlock onSubmit={d=>{setToast('Project prepared for '+d.name);setDialogOpen(false)}}/></U.Modal><U.Toast open={!!toast} onOpenChange={v=>!v&&setToast('')} title={toast} description="This is an interactive example."/></div>;
return <div className="showcase-grid">
<div className="showcase-column">
<Panel><div className="flex flex-wrap gap-2"><U.Button size="sm" onClick={()=>setToast('Button activated')}>Button <ArrowUpRight className="size-3"/></U.Button><U.Button tone="secondary" size="sm" onClick={()=>setToast('Secondary activated')}>Secondary</U.Button><U.Button tone="outline" size="sm" onClick={()=>setToast('Outline activated')}>Outline</U.Button></div><div className="mt-5 space-y-3"><U.InputGroup suffix={<Search className="size-3.5"/>}><U.Input placeholder="Your project name" aria-label="Demo project name"/></U.InputGroup><U.Textarea aria-label="Demo message" placeholder="Leave a thought…" rows={2}/></div><div className="my-5 flex items-center justify-between gap-3"><div className="flex gap-1.5"><U.Badge>Draft</U.Badge><U.Badge tone="success">Ready</U.Badge></div><U.Checkbox label="Select" checked={invite} onCheckedChange={v=>setInvite(v===true)}/></div><div className="flex flex-wrap gap-2"><U.Modal title="Invite someone new." description="Good work starts with the right people." trigger={<U.Button tone="outline" size="sm">Open dialog</U.Button>}><U.FormBlock onSubmit={d=>setToast('Invitation drafted for '+d.name)}/></U.Modal><U.ButtonGroup label="Display mode"><U.Button tone={compact?'primary':'outline'} size="sm" onClick={()=>setCompact(true)} aria-label="Grid view"><LayoutGrid className="size-3.5"/></U.Button><U.Button tone={compact?'outline':'primary'} size="sm" onClick={()=>setCompact(false)} aria-label="Code view"><Code2 className="size-3.5"/></U.Button></U.ButtonGroup>{menu}</div></Panel>
<Panel title="Invite to your workspace" description="Bring a fresh perspective to the table." action={<span className="icon-tile"><Mail className="size-4"/></span>}><form onSubmit={e=>{e.preventDefault();setToast('Invitation drafted for '+name);setName('')}}><div className="flex gap-2"><U.Input aria-label="Invite email" type="email" required value={name} onChange={e=>setName(e.target.value)} placeholder="name@example.com"/><U.Button type="submit" size="sm" aria-label="Prepare invitation"><ArrowRight className="size-4"/></U.Button></div></form><div className="mt-5 space-y-4">{[['Alex Rivers','alex@example.com','Owner'],['Sam Chen','sam@example.com','Editor']].map(([n,e,r])=><div key={n} className="flex items-center gap-3"><U.Avatar name={n}/><div className="min-w-0 flex-1"><p className="text-xs font-medium">{n}</p><p className="text-[10px] text-muted">{e}</p></div><span className="text-[10px] text-muted">{r}</span></div>)}</div><div className="mt-5 border-t border-line pt-4"><U.Switch label="Allow invitation links" checked={share} onCheckedChange={setShare}/></div></Panel>
<Panel title="Appearance" description="A familiar place to make your own."><U.ToggleGroup label="Theme preference" options={['Light','Dark','System']} value={theme} onValueChange={v=>v&&setTheme(v)}/><div className="mt-5"><Row><span className="text-xs">Density</span><span className="text-[10px] text-muted">{compact?'Comfortable':'Spacious'}</span></Row><U.Slider label="Density" defaultValue={[40]} onValueChange={v=>setCompact(v[0]<60)}/></div><U.Switch label="Reduce motion" checked={subscribed} onCheckedChange={setSubscribed}/></Panel>
<Panel className="bg-surface/45"><p className="font-editorial text-[25px] leading-[1.2] tracking-tight">Everything begins<br/>with a little curiosity.</p><p className="mt-4 text-[11px] leading-relaxed text-muted">Thoughtful components for what comes next.</p><a className="mt-6 inline-flex items-center gap-2 text-xs font-medium" href="#/docs">Explore Aretusa <ArrowUpRight className="size-3.5"/></a></Panel>
</div>
<div className="showcase-column">
<Panel title="Contribution history" description="A little progress, every month." action={<U.Select label="Period" value={period} onValueChange={setPeriod} options={[{value:'6m',label:'6 months'},{value:'3m',label:'3 months'}]}/>}><div className="mb-2 flex items-end gap-3"><span className="text-[32px] font-medium leading-none tracking-[-.06em]">{period==='6m'?'1,284':'896'}</span><span className="mb-1 inline-flex items-center gap-1 text-[10px] text-success"><ArrowUpRight className="size-3"/>12.8%</span></div><U.Chart data={data} label="Monthly contributions" kind="bar" compact/><div className="mt-4 border-t border-line pt-4"><Row><span className="text-[11px] text-muted">Next milestone</span><U.Badge>1,500 contributions</U.Badge></Row></div></Panel>
<Panel title="Your next milestone" description="Small steps. A clear direction." action={menu}><U.Progress label="Design system" value={68}/><div className="mt-5 flex items-center justify-between"><div className="flex -space-x-2"><U.Avatar name="Alex Rivers"/><U.Avatar name="Sam Chen"/><U.Avatar name="Jo Bell"/></div><span className="text-[10px] text-muted">3 contributors</span></div><div className="mt-5 grid grid-cols-2 gap-4 border-t border-line pt-4"><div><p className="text-[10px] text-muted">Due date</p><p className="mt-1.5 text-xs font-medium">October 24</p></div><div><p className="text-[10px] text-muted">Remaining</p><p className="mt-1.5 text-xs font-medium">8 components</p></div></div><U.Button tone="outline" size="sm" className="mt-5 w-full" onClick={()=>setToast('Milestone details opened')}>View details <ArrowUpRight className="size-3.5"/></U.Button></Panel>
<Panel title="Leave a thought" description="A conversation worth continuing." action={menu}><div className="min-h-28 space-y-3">{messages.map((m,i)=><U.Bubble key={i} side={i%2?'end':'start'}>{m}</U.Bubble>)}</div><form className="mt-5 rounded-xl border border-line bg-paper/40 p-3" onSubmit={e=>{e.preventDefault();if(message.trim()){setMessages(ms=>[...ms,message.trim()]);setMessage('')}}}><textarea aria-label="Conversation message" className="w-full resize-none bg-transparent text-xs outline-none placeholder:text-muted/70" rows={2} value={message} onChange={e=>setMessage(e.target.value)} placeholder="What are you thinking about?"/><Row><U.Tooltip content="Attachments are an example"><U.Button tone="quiet" size="sm" aria-label="About attachments" onClick={()=>setToast('This preview uses text messages')}><Paperclip className="size-3.5"/></U.Button></U.Tooltip><U.Button size="sm" type="submit" disabled={!message.trim()} aria-label="Send example message"><ArrowRight className="size-3.5"/></U.Button></Row></form></Panel>
<Panel><Row><span className="icon-tile"><CheckCircle2 className="size-5 text-success"/></span><U.Badge tone="success">All up to date</U.Badge></Row><p className="mt-5 text-sm font-medium">Your changes have a home.</p><p className="mt-2 text-[11px] leading-relaxed text-muted">Everything in this example is saved for this session.</p></Panel>
</div>
<div className="showcase-column">
<Panel title="A space for your work." description="Choose who gets a seat at the table."><div className="space-y-2">{[['team','Your team','A shared space for good ideas.',Globe],['private','Only you','A quiet place to work things out.',Lock]].map(([v,l,d,Icon])=>{const I=Icon as typeof Globe;return <button key={v as string} onClick={()=>setAudience(v as string)} className={'choice-card '+(audience===v?'choice-card-selected':'')} aria-pressed={audience===v}><span className="icon-tile"><I className="size-4"/></span><span className="flex-1 text-start"><span className="block text-xs font-medium">{l as string}</span><span className="mt-1 block text-[10px] text-muted">{d as string}</span></span><span className={'flex size-4 items-center justify-center rounded-full border '+(audience===v?'border-ink bg-ink text-paper':'border-line')}>{audience===v&&<Check className="size-2.5"/>}</span></button>})}</div><U.Button className="mt-5 w-full" size="sm" onClick={()=>setToast((audience==='team'?'Team':'Private')+' workspace selected')}>Continue <ArrowRight className="size-3.5"/></U.Button></Panel>
<Panel title="Project activity" description="The shape of your week."><U.Chart label="Activity by discipline" kind="pie" compact data={[{name:'Design',value:45},{name:'Code',value:32},{name:'Research',value:23}]}/><div className="mt-3 space-y-2.5">{[['Design','45%','bg-terracotta'],['Code','32%','bg-gold'],['Research','23%','bg-chart-3']].map(([n,v,c])=><Row key={n}><span className="flex items-center gap-2 text-[11px]"><span className={'size-1.5 rounded-full '+c}/>{n}</span><span className="font-mono text-[10px] text-muted">{v}</span></Row>)}</div></Panel>
<Panel title="Stay in the loop" description="Updates that respect your attention."><div className="space-y-5"><U.Switch label="Product updates" defaultChecked/><U.Switch label="Community stories"/><U.Switch label="Release notes" defaultChecked/></div><U.Separator/><Row><p className="max-w-40 text-[10px] leading-relaxed text-muted">You can change these anytime.</p><U.Button size="sm" onClick={()=>setToast('Example preferences saved')}>Save</U.Button></Row></Panel>
<Panel title="Field notes" description="A first draft of something good." action={menu}><p className="font-editorial text-[24px] leading-tight tracking-tight">Design is a thousand<br/>small decisions.</p><div className="mt-5 flex items-center justify-between border-t border-line pt-4"><span className="text-[10px] text-muted">Aretusa / Notes 001</span><U.Button size="sm" tone="quiet" onClick={()=>setToast('Example added to favorites')} aria-label="Favorite note"><Heart className="size-3.5"/></U.Button></div></Panel>
</div><U.Toast open={!!toast} onOpenChange={v=>!v&&setToast('')} title={toast} description="Interactive example. No external data is sent."/></div>;
}

