export const catalog = [
  {
    id: "aspect-ratio",
    name: "Aspect Ratio",
    module: "basic",
    exportName: "AspectRatio",
    description:
      "A composable aspect ratio for coherent, adaptable interfaces.",
  },
  {
    id: "avatar",
    name: "Avatar",
    module: "basic",
    exportName: "Avatar",
    description: "A composable avatar for coherent, adaptable interfaces.",
  },
  {
    id: "badge",
    name: "Badge",
    module: "basic",
    exportName: "Badge",
    description: "A composable badge for coherent, adaptable interfaces.",
  },
  {
    id: "button",
    name: "Button",
    module: "basic",
    exportName: "Button",
    description: "A clear action with size, tone, disabled and loading states.",
  },
  {
    id: "button-group",
    name: "Button Group",
    module: "basic",
    exportName: "ButtonGroup",
    description:
      "A composable button group for coherent, adaptable interfaces.",
  },
  {
    id: "card",
    name: "Card",
    module: "basic",
    exportName: "Card",
    description: "A composable card for coherent, adaptable interfaces.",
  },
  {
    id: "direction",
    name: "Direction",
    module: "basic",
    exportName: "Direction",
    description: "A composable direction for coherent, adaptable interfaces.",
  },
  {
    id: "empty",
    name: "Empty",
    module: "basic",
    exportName: "Empty",
    description: "A composable empty for coherent, adaptable interfaces.",
  },
  {
    id: "item",
    name: "Item",
    module: "basic",
    exportName: "Item",
    description: "A composable item for coherent, adaptable interfaces.",
  },
  {
    id: "kbd",
    name: "Kbd",
    module: "basic",
    exportName: "Kbd",
    description: "A composable kbd for coherent, adaptable interfaces.",
  },
  {
    id: "progress",
    name: "Progress",
    module: "basic",
    exportName: "Progress",
    description: "A composable progress for coherent, adaptable interfaces.",
  },
  {
    id: "separator",
    name: "Separator",
    module: "basic",
    exportName: "Separator",
    description: "A composable separator for coherent, adaptable interfaces.",
  },
  {
    id: "skeleton",
    name: "Skeleton",
    module: "basic",
    exportName: "Skeleton",
    description: "A composable skeleton for coherent, adaptable interfaces.",
  },
  {
    id: "spinner",
    name: "Spinner",
    module: "basic",
    exportName: "Spinner",
    description: "A composable spinner for coherent, adaptable interfaces.",
  },
  {
    id: "typography",
    name: "Typography",
    module: "basic",
    exportName: "Typography",
    description: "A composable typography for coherent, adaptable interfaces.",
  },
  {
    id: "alert",
    name: "Alert",
    module: "basic",
    exportName: "Alert",
    description: "A composable alert for coherent, adaptable interfaces.",
  },
  {
    id: "calendar",
    name: "Calendar",
    module: "forms",
    exportName: "Calendar",
    description: "Explore and select dates in a month grid.",
  },
  {
    id: "checkbox",
    name: "Checkbox",
    module: "forms",
    exportName: "Checkbox",
    description: "A composable checkbox for coherent, adaptable interfaces.",
  },
  {
    id: "combobox",
    name: "Combobox",
    module: "forms",
    exportName: "Combobox",
    description: "A text input with native datalist suggestions.",
  },
  {
    id: "date-picker",
    name: "Date Picker",
    module: "forms",
    exportName: "DatePicker",
    description:
      "A native date control that follows the browser and device conventions.",
  },
  {
    id: "field",
    name: "Field",
    module: "forms",
    exportName: "Field",
    description: "Connect a control to its label, hint and validation message.",
  },
  {
    id: "input",
    name: "Input",
    module: "forms",
    exportName: "Input",
    description: "A composable input for coherent, adaptable interfaces.",
  },
  {
    id: "input-group",
    name: "Input Group",
    module: "forms",
    exportName: "InputGroup",
    description: "A composable input group for coherent, adaptable interfaces.",
  },
  {
    id: "input-otp",
    name: "Input OTP",
    module: "forms",
    exportName: "InputOTP",
    description:
      "A numeric one-time-code input with paste and autofill support.",
  },
  {
    id: "label",
    name: "Label",
    module: "forms",
    exportName: "Label",
    description: "A composable label for coherent, adaptable interfaces.",
  },
  {
    id: "native-select",
    name: "Native Select",
    module: "forms",
    exportName: "NativeSelect",
    description:
      "A composable native select for coherent, adaptable interfaces.",
  },
  {
    id: "radio-group",
    name: "Radio Group",
    module: "forms",
    exportName: "RadioGroup",
    description: "A composable radio group for coherent, adaptable interfaces.",
  },
  {
    id: "select",
    name: "Select",
    module: "forms",
    exportName: "Select",
    description:
      "Choose one value with keyboard navigation and a floating list.",
  },
  {
    id: "slider",
    name: "Slider",
    module: "forms",
    exportName: "Slider",
    description: "A composable slider for coherent, adaptable interfaces.",
  },
  {
    id: "switch",
    name: "Switch",
    module: "forms",
    exportName: "Switch",
    description: "A composable switch for coherent, adaptable interfaces.",
  },
  {
    id: "textarea",
    name: "Textarea",
    module: "forms",
    exportName: "Textarea",
    description: "A composable textarea for coherent, adaptable interfaces.",
  },
  {
    id: "toggle",
    name: "Toggle",
    module: "forms",
    exportName: "Toggle",
    description: "A composable toggle for coherent, adaptable interfaces.",
  },
  {
    id: "toggle-group",
    name: "Toggle Group",
    module: "forms",
    exportName: "ToggleGroup",
    description:
      "A composable toggle group for coherent, adaptable interfaces.",
  },
  {
    id: "alert-dialog",
    name: "Alert Dialog",
    module: "overlays",
    exportName: "AlertDialog",
    description:
      "A composable alert dialog for coherent, adaptable interfaces.",
  },
  {
    id: "dialog",
    name: "Dialog",
    module: "overlays",
    exportName: "Dialog",
    description:
      "A modal conversation with focus containment and a clear way back.",
  },
  {
    id: "drawer",
    name: "Drawer",
    module: "overlays",
    exportName: "Drawer",
    description: "A bottom modal panel for a focused mobile task.",
  },
  {
    id: "hover-card",
    name: "Hover Card",
    module: "overlays",
    exportName: "HoverCard",
    description: "A composable hover card for coherent, adaptable interfaces.",
  },
  {
    id: "popover",
    name: "Popover",
    module: "overlays",
    exportName: "Popover",
    description: "A composable popover for coherent, adaptable interfaces.",
  },
  {
    id: "sheet",
    name: "Sheet",
    module: "overlays",
    exportName: "Sheet",
    description: "A composable sheet for coherent, adaptable interfaces.",
  },
  {
    id: "toast",
    name: "Toast",
    module: "overlays",
    exportName: "ToastDemo",
    description: "A temporary message with a dismiss action.",
  },
  {
    id: "tooltip",
    name: "Tooltip",
    module: "overlays",
    exportName: "Tooltip",
    description: "A composable tooltip for coherent, adaptable interfaces.",
  },
  {
    id: "accordion",
    name: "Accordion",
    module: "navigation",
    exportName: "Accordion",
    description: "A composable accordion for coherent, adaptable interfaces.",
  },
  {
    id: "breadcrumb",
    name: "Breadcrumb",
    module: "navigation",
    exportName: "Breadcrumb",
    description: "A composable breadcrumb for coherent, adaptable interfaces.",
  },
  {
    id: "collapsible",
    name: "Collapsible",
    module: "navigation",
    exportName: "Collapsible",
    description: "A composable collapsible for coherent, adaptable interfaces.",
  },
  {
    id: "command",
    name: "Command",
    module: "navigation",
    exportName: "Command",
    description: "A composable command for coherent, adaptable interfaces.",
  },
  {
    id: "context-menu",
    name: "Context Menu",
    module: "navigation",
    exportName: "ContextMenu",
    description:
      "A composable context menu for coherent, adaptable interfaces.",
  },
  {
    id: "dropdown-menu",
    name: "Dropdown Menu",
    module: "navigation",
    exportName: "DropdownMenu",
    description:
      "A composable dropdown menu for coherent, adaptable interfaces.",
  },
  {
    id: "menubar",
    name: "Menubar",
    module: "navigation",
    exportName: "Menubar",
    description: "A composable menubar for coherent, adaptable interfaces.",
  },
  {
    id: "navigation-menu",
    name: "Navigation Menu",
    module: "navigation",
    exportName: "NavigationMenu",
    description:
      "A composable navigation menu for coherent, adaptable interfaces.",
  },
  {
    id: "pagination",
    name: "Pagination",
    module: "navigation",
    exportName: "Pagination",
    description: "A composable pagination for coherent, adaptable interfaces.",
  },
  {
    id: "scroll-area",
    name: "Scroll Area",
    module: "navigation",
    exportName: "ScrollArea",
    description: "A composable scroll area for coherent, adaptable interfaces.",
  },
  {
    id: "sidebar",
    name: "Sidebar",
    module: "navigation",
    exportName: "Sidebar",
    description: "A responsive side navigation and content composition.",
  },
  {
    id: "tabs",
    name: "Tabs",
    module: "navigation",
    exportName: "Tabs",
    description: "A composable tabs for coherent, adaptable interfaces.",
  },
  {
    id: "carousel",
    name: "Carousel",
    module: "data",
    exportName: "Carousel",
    description: "A composable carousel for coherent, adaptable interfaces.",
  },
  {
    id: "chart",
    name: "Chart",
    module: "data",
    exportName: "Chart",
    description:
      "A line chart with accessible data and a text-table alternative.",
  },
  {
    id: "data-table",
    name: "Data Table",
    module: "data",
    exportName: "DataTable",
    description:
      "Filter, sort and paginate records in a composable table recipe.",
  },
  {
    id: "resizable",
    name: "Resizable",
    module: "data",
    exportName: "Resizable",
    description: "Two panes with an accessible range control for the split.",
  },
  {
    id: "table",
    name: "Table",
    module: "data",
    exportName: "Table",
    description: "A composable table for coherent, adaptable interfaces.",
  },
  {
    id: "attachment",
    name: "Attachment",
    module: "conversation",
    exportName: "Attachment",
    description: "A composable attachment for coherent, adaptable interfaces.",
  },
  {
    id: "bubble",
    name: "Bubble",
    module: "conversation",
    exportName: "Bubble",
    description: "A composable bubble for coherent, adaptable interfaces.",
  },
  {
    id: "marker",
    name: "Marker",
    module: "conversation",
    exportName: "Marker",
    description: "A composable marker for coherent, adaptable interfaces.",
  },
  {
    id: "message",
    name: "Message",
    module: "conversation",
    exportName: "Message",
    description: "A composable message for coherent, adaptable interfaces.",
  },
  {
    id: "message-scroller",
    name: "Message Scroller",
    module: "conversation",
    exportName: "MessageScroller",
    description:
      "A composable message scroller for coherent, adaptable interfaces.",
  },
  {
    id: "questionnaire",
    name: "Questionnaire",
    module: "conversation",
    exportName: "Questionnaire",
    description: "A guided sequence of required single-choice questions.",
  },
] as const;
export type ComponentId = (typeof catalog)[number]["id"];
